# Generated by Django 2.0.2 on 2018-02-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180221_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='nome',
            new_name='name',
        ),
    ]
